# Generated by Django 5.1.2 on 2024-11-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admission',
            field=models.IntegerField(default=0),
        ),
    ]
